// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.changePasswordStmt, err = db.PrepareContext(ctx, changePassword); err != nil {
		return nil, fmt.Errorf("error preparing query ChangePassword: %w", err)
	}
	if q.createEmailVerificationTokenStmt, err = db.PrepareContext(ctx, createEmailVerificationToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateEmailVerificationToken: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteEmailVerificationTokenStmt, err = db.PrepareContext(ctx, deleteEmailVerificationToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEmailVerificationToken: %w", err)
	}
	if q.deleteExpiredEmailVerificationTokensStmt, err = db.PrepareContext(ctx, deleteExpiredEmailVerificationTokens); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredEmailVerificationTokens: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.getCountryByIDStmt, err = db.PrepareContext(ctx, getCountryByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCountryByID: %w", err)
	}
	if q.getCountryByNameStmt, err = db.PrepareContext(ctx, getCountryByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetCountryByName: %w", err)
	}
	if q.getEmailVerificationTokenStmt, err = db.PrepareContext(ctx, getEmailVerificationToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetEmailVerificationToken: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.getUserByUsernameOrEmailStmt, err = db.PrepareContext(ctx, getUserByUsernameOrEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsernameOrEmail: %w", err)
	}
	if q.getUserPasswordStmt, err = db.PrepareContext(ctx, getUserPassword); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserPassword: %w", err)
	}
	if q.listCitiesByCountryIDStmt, err = db.PrepareContext(ctx, listCitiesByCountryID); err != nil {
		return nil, fmt.Errorf("error preparing query ListCitiesByCountryID: %w", err)
	}
	if q.listCountriesStmt, err = db.PrepareContext(ctx, listCountries); err != nil {
		return nil, fmt.Errorf("error preparing query ListCountries: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.updateUserProfileStmt, err = db.PrepareContext(ctx, updateUserProfile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserProfile: %w", err)
	}
	if q.updateUserStatusStmt, err = db.PrepareContext(ctx, updateUserStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserStatus: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.changePasswordStmt != nil {
		if cerr := q.changePasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing changePasswordStmt: %w", cerr)
		}
	}
	if q.createEmailVerificationTokenStmt != nil {
		if cerr := q.createEmailVerificationTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createEmailVerificationTokenStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteEmailVerificationTokenStmt != nil {
		if cerr := q.deleteEmailVerificationTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEmailVerificationTokenStmt: %w", cerr)
		}
	}
	if q.deleteExpiredEmailVerificationTokensStmt != nil {
		if cerr := q.deleteExpiredEmailVerificationTokensStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredEmailVerificationTokensStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.getCountryByIDStmt != nil {
		if cerr := q.getCountryByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCountryByIDStmt: %w", cerr)
		}
	}
	if q.getCountryByNameStmt != nil {
		if cerr := q.getCountryByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCountryByNameStmt: %w", cerr)
		}
	}
	if q.getEmailVerificationTokenStmt != nil {
		if cerr := q.getEmailVerificationTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEmailVerificationTokenStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameOrEmailStmt != nil {
		if cerr := q.getUserByUsernameOrEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameOrEmailStmt: %w", cerr)
		}
	}
	if q.getUserPasswordStmt != nil {
		if cerr := q.getUserPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserPasswordStmt: %w", cerr)
		}
	}
	if q.listCitiesByCountryIDStmt != nil {
		if cerr := q.listCitiesByCountryIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCitiesByCountryIDStmt: %w", cerr)
		}
	}
	if q.listCountriesStmt != nil {
		if cerr := q.listCountriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCountriesStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.updateUserProfileStmt != nil {
		if cerr := q.updateUserProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserProfileStmt: %w", cerr)
		}
	}
	if q.updateUserStatusStmt != nil {
		if cerr := q.updateUserStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStatusStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                       DBTX
	tx                                       *sql.Tx
	changePasswordStmt                       *sql.Stmt
	createEmailVerificationTokenStmt         *sql.Stmt
	createUserStmt                           *sql.Stmt
	deleteEmailVerificationTokenStmt         *sql.Stmt
	deleteExpiredEmailVerificationTokensStmt *sql.Stmt
	deleteUserStmt                           *sql.Stmt
	getCountryByIDStmt                       *sql.Stmt
	getCountryByNameStmt                     *sql.Stmt
	getEmailVerificationTokenStmt            *sql.Stmt
	getUserStmt                              *sql.Stmt
	getUserByUsernameOrEmailStmt             *sql.Stmt
	getUserPasswordStmt                      *sql.Stmt
	listCitiesByCountryIDStmt                *sql.Stmt
	listCountriesStmt                        *sql.Stmt
	listUsersStmt                            *sql.Stmt
	updateUserProfileStmt                    *sql.Stmt
	updateUserStatusStmt                     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                       tx,
		tx:                                       tx,
		changePasswordStmt:                       q.changePasswordStmt,
		createEmailVerificationTokenStmt:         q.createEmailVerificationTokenStmt,
		createUserStmt:                           q.createUserStmt,
		deleteEmailVerificationTokenStmt:         q.deleteEmailVerificationTokenStmt,
		deleteExpiredEmailVerificationTokensStmt: q.deleteExpiredEmailVerificationTokensStmt,
		deleteUserStmt:                           q.deleteUserStmt,
		getCountryByIDStmt:                       q.getCountryByIDStmt,
		getCountryByNameStmt:                     q.getCountryByNameStmt,
		getEmailVerificationTokenStmt:            q.getEmailVerificationTokenStmt,
		getUserStmt:                              q.getUserStmt,
		getUserByUsernameOrEmailStmt:             q.getUserByUsernameOrEmailStmt,
		getUserPasswordStmt:                      q.getUserPasswordStmt,
		listCitiesByCountryIDStmt:                q.listCitiesByCountryIDStmt,
		listCountriesStmt:                        q.listCountriesStmt,
		listUsersStmt:                            q.listUsersStmt,
		updateUserProfileStmt:                    q.updateUserProfileStmt,
		updateUserStatusStmt:                     q.updateUserStatusStmt,
	}
}
