// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql"
)

type User struct {
	ID           int32        `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	Password     string       `json:"password"`
	Name         string       `json:"name"`
	Country      string       `json:"country"`
	City         string       `json:"city"`
	LegalAddress string       `json:"legal_address"`
	VatNumber    string       `json:"vat_number"`
	Status       string       `json:"status"`
	Language     string       `json:"language"`
	Created      sql.NullTime `json:"created"`
	Updated      sql.NullTime `json:"updated"`
}
