// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql"
	"time"

	"github.com/aleksjovanovic/cargo-agent/internal/models"
)

type City struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	CountryID int32          `json:"country_id"`
	Latitude  sql.NullString `json:"latitude"`
	Longitude sql.NullString `json:"longitude"`
}

type Country struct {
	ID         int32          `json:"id"`
	Name       string         `json:"name"`
	Code       string         `json:"code"`
	Alpha3Code string         `json:"alpha3_code"`
	EuMember   sql.NullBool   `json:"eu_member"`
	Continent  sql.NullString `json:"continent"`
}

type EmailVerificationToken struct {
	ID         int32     `json:"id"`
	UserID     int32     `json:"user_id"`
	Token      string    `json:"token"`
	CreatedAt  time.Time `json:"created_at"`
	ValidUntil time.Time `json:"valid_until"`
}

type User struct {
	ID           int32             `json:"id"`
	Username     string            `json:"username"`
	Email        string            `json:"email"`
	Password     string            `json:"password"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	CreatedAt    sql.NullTime      `json:"created_at"`
	UpdatedAt    sql.NullTime      `json:"updated_at"`
	DeletedAt    sql.NullTime      `json:"deleted_at"`
}
