// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/aleksjovanovic/cargo-agent/internal/models"
)

const ChangePassword = `-- name: ChangePassword :exec
UPDATE users
SET password=$2, updated_at=$3
WHERE id = $1
`

type ChangePasswordParams struct {
	ID        int32        `json:"id"`
	Password  string       `json:"password"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) error {
	_, err := q.exec(ctx, q.changePasswordStmt, ChangePassword, arg.ID, arg.Password, arg.UpdatedAt)
	return err
}

const CreateCargoOffer = `-- name: CreateCargoOffer :one
INSERT INTO cargo_offers (
    created_by,
    origin_country_id, origin_city_id,
    destination_country_id, destination_city_id,
    loading_places, unloading_places,
    ready_to_load_by, delivery_deadline,
    load_type, truck_type,
    weight_t, volume_m3, pallets, palletized,
    temperature_min_c, temperature_max_c,
    published_at, expires_at,
    price, currency, notes, status
) VALUES (
    $1,
    $2, $3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10::load_type,
    $11::truck_type,
    $12, $13, $14, $15,
    $16, $17,
    $18, $19,
    $20, $21, $22,
    $23::offer_status
)
RETURNING
    id,
    created_by,
    origin_country_id, origin_city_id,
    destination_country_id, destination_city_id,
    loading_places, unloading_places,
    ready_to_load_by, delivery_deadline,
    load_type::text   AS load_type,
    truck_type::text  AS truck_type,
    weight_t, volume_m3, pallets, palletized,
    temperature_min_c, temperature_max_c,
    published_at, expires_at,
    price, currency, notes,
    status::text      AS status,
    created_at, updated_at
`

type CreateCargoOfferParams struct {
	CreatedBy            int32          `json:"created_by"`
	OriginCountryID      int32          `json:"origin_country_id"`
	OriginCityID         int32          `json:"origin_city_id"`
	DestinationCountryID int32          `json:"destination_country_id"`
	DestinationCityID    int32          `json:"destination_city_id"`
	LoadingPlaces        int32          `json:"loading_places"`
	UnloadingPlaces      int32          `json:"unloading_places"`
	ReadyToLoadBy        time.Time      `json:"ready_to_load_by"`
	DeliveryDeadline     time.Time      `json:"delivery_deadline"`
	LoadType             string         `json:"load_type"`
	TruckType            string         `json:"truck_type"`
	WeightT              string         `json:"weight_t"`
	VolumeM3             sql.NullString `json:"volume_m3"`
	Pallets              sql.NullInt32  `json:"pallets"`
	Palletized           sql.NullBool   `json:"palletized"`
	TemperatureMinC      sql.NullString `json:"temperature_min_c"`
	TemperatureMaxC      sql.NullString `json:"temperature_max_c"`
	PublishedAt          sql.NullTime   `json:"published_at"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	Price                sql.NullString `json:"price"`
	Currency             sql.NullString `json:"currency"`
	Notes                sql.NullString `json:"notes"`
	Status               string         `json:"status"`
}

type CreateCargoOfferRow struct {
	ID                   int32          `json:"id"`
	CreatedBy            int32          `json:"created_by"`
	OriginCountryID      int32          `json:"origin_country_id"`
	OriginCityID         int32          `json:"origin_city_id"`
	DestinationCountryID int32          `json:"destination_country_id"`
	DestinationCityID    int32          `json:"destination_city_id"`
	LoadingPlaces        int32          `json:"loading_places"`
	UnloadingPlaces      int32          `json:"unloading_places"`
	ReadyToLoadBy        time.Time      `json:"ready_to_load_by"`
	DeliveryDeadline     time.Time      `json:"delivery_deadline"`
	LoadType             string         `json:"load_type"`
	TruckType            string         `json:"truck_type"`
	WeightT              string         `json:"weight_t"`
	VolumeM3             sql.NullString `json:"volume_m3"`
	Pallets              sql.NullInt32  `json:"pallets"`
	Palletized           sql.NullBool   `json:"palletized"`
	TemperatureMinC      sql.NullString `json:"temperature_min_c"`
	TemperatureMaxC      sql.NullString `json:"temperature_max_c"`
	PublishedAt          sql.NullTime   `json:"published_at"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	Price                sql.NullString `json:"price"`
	Currency             sql.NullString `json:"currency"`
	Notes                sql.NullString `json:"notes"`
	Status               string         `json:"status"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateCargoOffer(ctx context.Context, arg CreateCargoOfferParams) (CreateCargoOfferRow, error) {
	row := q.queryRow(ctx, q.createCargoOfferStmt, CreateCargoOffer,
		arg.CreatedBy,
		arg.OriginCountryID,
		arg.OriginCityID,
		arg.DestinationCountryID,
		arg.DestinationCityID,
		arg.LoadingPlaces,
		arg.UnloadingPlaces,
		arg.ReadyToLoadBy,
		arg.DeliveryDeadline,
		arg.LoadType,
		arg.TruckType,
		arg.WeightT,
		arg.VolumeM3,
		arg.Pallets,
		arg.Palletized,
		arg.TemperatureMinC,
		arg.TemperatureMaxC,
		arg.PublishedAt,
		arg.ExpiresAt,
		arg.Price,
		arg.Currency,
		arg.Notes,
		arg.Status,
	)
	var i CreateCargoOfferRow
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.OriginCountryID,
		&i.OriginCityID,
		&i.DestinationCountryID,
		&i.DestinationCityID,
		&i.LoadingPlaces,
		&i.UnloadingPlaces,
		&i.ReadyToLoadBy,
		&i.DeliveryDeadline,
		&i.LoadType,
		&i.TruckType,
		&i.WeightT,
		&i.VolumeM3,
		&i.Pallets,
		&i.Palletized,
		&i.TemperatureMinC,
		&i.TemperatureMaxC,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.Price,
		&i.Currency,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (user_id, token, valid_until)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, created_at, valid_until
`

type CreateEmailVerificationTokenParams struct {
	UserID     int32     `json:"user_id"`
	Token      string    `json:"token"`
	ValidUntil time.Time `json:"valid_until"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.queryRow(ctx, q.createEmailVerificationTokenStmt, CreateEmailVerificationToken, arg.UserID, arg.Token, arg.ValidUntil)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ValidUntil,
	)
	return i, err
}

const CreateTruckAvailability = `-- name: CreateTruckAvailability :one
INSERT INTO truck_availability (
  created_by,
  start_country_id, start_city_id,
  end_country_id, end_city_id,
  available_from, available_to,
  truck_type, max_weight_t, max_volume_m3,
  full_load, partial_load,
  loading_places, unloading_places,
  published_at, expires_at,
  poster_name, price_per_km, currency, notes, status
) VALUES (
  $1,
  $2, $3,
  $4, $5,
  $6, $7,
  $8, $9, $10,
  $11, $12,
  $13, $14,
  $15, $16,
  $17, $18, $19, $20, $21
)
RETURNING id, created_by, start_country_id, start_city_id, end_country_id, end_city_id, available_from, available_to, truck_type, max_weight_t, max_volume_m3, full_load, partial_load, loading_places, unloading_places, published_at, expires_at, poster_name, price_per_km, currency, notes, status, created_at, updated_at
`

type CreateTruckAvailabilityParams struct {
	CreatedBy       int32          `json:"created_by"`
	StartCountryID  int32          `json:"start_country_id"`
	StartCityID     int32          `json:"start_city_id"`
	EndCountryID    sql.NullInt32  `json:"end_country_id"`
	EndCityID       sql.NullInt32  `json:"end_city_id"`
	AvailableFrom   time.Time      `json:"available_from"`
	AvailableTo     time.Time      `json:"available_to"`
	TruckType       string         `json:"truck_type"`
	MaxWeightT      string         `json:"max_weight_t"`
	MaxVolumeM3     sql.NullString `json:"max_volume_m3"`
	FullLoad        bool           `json:"full_load"`
	PartialLoad     bool           `json:"partial_load"`
	LoadingPlaces   int32          `json:"loading_places"`
	UnloadingPlaces int32          `json:"unloading_places"`
	PublishedAt     sql.NullTime   `json:"published_at"`
	ExpiresAt       sql.NullTime   `json:"expires_at"`
	PosterName      string         `json:"poster_name"`
	PricePerKm      sql.NullString `json:"price_per_km"`
	Currency        sql.NullString `json:"currency"`
	Notes           sql.NullString `json:"notes"`
	Status          string         `json:"status"`
}

func (q *Queries) CreateTruckAvailability(ctx context.Context, arg CreateTruckAvailabilityParams) (TruckAvailability, error) {
	row := q.queryRow(ctx, q.createTruckAvailabilityStmt, CreateTruckAvailability,
		arg.CreatedBy,
		arg.StartCountryID,
		arg.StartCityID,
		arg.EndCountryID,
		arg.EndCityID,
		arg.AvailableFrom,
		arg.AvailableTo,
		arg.TruckType,
		arg.MaxWeightT,
		arg.MaxVolumeM3,
		arg.FullLoad,
		arg.PartialLoad,
		arg.LoadingPlaces,
		arg.UnloadingPlaces,
		arg.PublishedAt,
		arg.ExpiresAt,
		arg.PosterName,
		arg.PricePerKm,
		arg.Currency,
		arg.Notes,
		arg.Status,
	)
	var i TruckAvailability
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.StartCountryID,
		&i.StartCityID,
		&i.EndCountryID,
		&i.EndCityID,
		&i.AvailableFrom,
		&i.AvailableTo,
		&i.TruckType,
		&i.MaxWeightT,
		&i.MaxVolumeM3,
		&i.FullLoad,
		&i.PartialLoad,
		&i.LoadingPlaces,
		&i.UnloadingPlaces,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.PosterName,
		&i.PricePerKm,
		&i.Currency,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateUser = `-- name: CreateUser :one
INSERT INTO users(username, email, password, name, country, city, legal_address, vat_number, language, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, username, email, name, country, city, legal_address, vat_number, status, language, created_at, updated_at
`

type CreateUserParams struct {
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	Password     string       `json:"password"`
	Name         string       `json:"name"`
	Country      string       `json:"country"`
	City         string       `json:"city"`
	LegalAddress string       `json:"legal_address"`
	VatNumber    string       `json:"vat_number"`
	Language     string       `json:"language"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type CreateUserRow struct {
	ID           int32             `json:"id"`
	Username     string            `json:"username"`
	Email        string            `json:"email"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	CreatedAt    sql.NullTime      `json:"created_at"`
	UpdatedAt    sql.NullTime      `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, CreateUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Name,
		arg.Country,
		arg.City,
		arg.LegalAddress,
		arg.VatNumber,
		arg.Language,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Country,
		&i.City,
		&i.LegalAddress,
		&i.VatNumber,
		&i.Status,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteEmailVerificationToken = `-- name: DeleteEmailVerificationToken :exec
DELETE FROM email_verification_tokens
WHERE token = $1
`

func (q *Queries) DeleteEmailVerificationToken(ctx context.Context, token string) error {
	_, err := q.exec(ctx, q.deleteEmailVerificationTokenStmt, DeleteEmailVerificationToken, token)
	return err
}

const DeleteExpiredEmailVerificationTokens = `-- name: DeleteExpiredEmailVerificationTokens :exec
DELETE FROM email_verification_tokens
WHERE valid_until < now()
`

func (q *Queries) DeleteExpiredEmailVerificationTokens(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteExpiredEmailVerificationTokensStmt, DeleteExpiredEmailVerificationTokens)
	return err
}

const DeleteUser = `-- name: DeleteUser :exec
UPDATE users
SET status = 'deleted',
    deleted_at = $2
WHERE id = $1 AND status <> 'deleted'
`

type DeleteUserParams struct {
	ID        int32        `json:"id"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.exec(ctx, q.deleteUserStmt, DeleteUser, arg.ID, arg.DeletedAt)
	return err
}

const GetCargoOffer = `-- name: GetCargoOffer :one
SELECT
    id,
    created_by,
    origin_country_id, origin_city_id,
    destination_country_id, destination_city_id,
    loading_places, unloading_places,
    ready_to_load_by, delivery_deadline,
    load_type::text   AS load_type,
    truck_type::text  AS truck_type,
    weight_t, volume_m3, pallets, palletized,
    temperature_min_c, temperature_max_c,
    published_at, expires_at,
    price, currency, notes,
    status::text      AS status,
    created_at, updated_at
FROM cargo_offers
WHERE id = $1
LIMIT 1
`

type GetCargoOfferRow struct {
	ID                   int32          `json:"id"`
	CreatedBy            int32          `json:"created_by"`
	OriginCountryID      int32          `json:"origin_country_id"`
	OriginCityID         int32          `json:"origin_city_id"`
	DestinationCountryID int32          `json:"destination_country_id"`
	DestinationCityID    int32          `json:"destination_city_id"`
	LoadingPlaces        int32          `json:"loading_places"`
	UnloadingPlaces      int32          `json:"unloading_places"`
	ReadyToLoadBy        time.Time      `json:"ready_to_load_by"`
	DeliveryDeadline     time.Time      `json:"delivery_deadline"`
	LoadType             string         `json:"load_type"`
	TruckType            string         `json:"truck_type"`
	WeightT              string         `json:"weight_t"`
	VolumeM3             sql.NullString `json:"volume_m3"`
	Pallets              sql.NullInt32  `json:"pallets"`
	Palletized           sql.NullBool   `json:"palletized"`
	TemperatureMinC      sql.NullString `json:"temperature_min_c"`
	TemperatureMaxC      sql.NullString `json:"temperature_max_c"`
	PublishedAt          sql.NullTime   `json:"published_at"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	Price                sql.NullString `json:"price"`
	Currency             sql.NullString `json:"currency"`
	Notes                sql.NullString `json:"notes"`
	Status               string         `json:"status"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetCargoOffer(ctx context.Context, id int32) (GetCargoOfferRow, error) {
	row := q.queryRow(ctx, q.getCargoOfferStmt, GetCargoOffer, id)
	var i GetCargoOfferRow
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.OriginCountryID,
		&i.OriginCityID,
		&i.DestinationCountryID,
		&i.DestinationCityID,
		&i.LoadingPlaces,
		&i.UnloadingPlaces,
		&i.ReadyToLoadBy,
		&i.DeliveryDeadline,
		&i.LoadType,
		&i.TruckType,
		&i.WeightT,
		&i.VolumeM3,
		&i.Pallets,
		&i.Palletized,
		&i.TemperatureMinC,
		&i.TemperatureMaxC,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.Price,
		&i.Currency,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetCountryByID = `-- name: GetCountryByID :one
SELECT id, name, code, alpha3_code, eu_member, continent
FROM countries
WHERE id = $1
`

func (q *Queries) GetCountryByID(ctx context.Context, id int32) (Country, error) {
	row := q.queryRow(ctx, q.getCountryByIDStmt, GetCountryByID, id)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Alpha3Code,
		&i.EuMember,
		&i.Continent,
	)
	return i, err
}

const GetCountryByName = `-- name: GetCountryByName :one
SELECT id, name, code, alpha3_code, eu_member, continent
FROM countries
WHERE Lower(name) = Lower($1)
`

func (q *Queries) GetCountryByName(ctx context.Context, lower string) (Country, error) {
	row := q.queryRow(ctx, q.getCountryByNameStmt, GetCountryByName, lower)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Alpha3Code,
		&i.EuMember,
		&i.Continent,
	)
	return i, err
}

const GetEmailVerificationToken = `-- name: GetEmailVerificationToken :one
SELECT id, user_id, token, created_at, valid_until
FROM email_verification_tokens
WHERE token = $1
LIMIT 1
`

func (q *Queries) GetEmailVerificationToken(ctx context.Context, token string) (EmailVerificationToken, error) {
	row := q.queryRow(ctx, q.getEmailVerificationTokenStmt, GetEmailVerificationToken, token)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ValidUntil,
	)
	return i, err
}

const GetTruckAvailability = `-- name: GetTruckAvailability :one
SELECT id, created_by, start_country_id, start_city_id, end_country_id, end_city_id, available_from, available_to, truck_type, max_weight_t, max_volume_m3, full_load, partial_load, loading_places, unloading_places, published_at, expires_at, poster_name, price_per_km, currency, notes, status, created_at, updated_at FROM truck_availability WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTruckAvailability(ctx context.Context, id int32) (TruckAvailability, error) {
	row := q.queryRow(ctx, q.getTruckAvailabilityStmt, GetTruckAvailability, id)
	var i TruckAvailability
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.StartCountryID,
		&i.StartCityID,
		&i.EndCountryID,
		&i.EndCityID,
		&i.AvailableFrom,
		&i.AvailableTo,
		&i.TruckType,
		&i.MaxWeightT,
		&i.MaxVolumeM3,
		&i.FullLoad,
		&i.PartialLoad,
		&i.LoadingPlaces,
		&i.UnloadingPlaces,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.PosterName,
		&i.PricePerKm,
		&i.Currency,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUser = `-- name: GetUser :one
SELECT id, username, email, name, country, city, legal_address, vat_number, status, language, created_at, updated_at
FROM users
WHERE id = $1
AND status = 'active'
`

type GetUserRow struct {
	ID           int32             `json:"id"`
	Username     string            `json:"username"`
	Email        string            `json:"email"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	CreatedAt    sql.NullTime      `json:"created_at"`
	UpdatedAt    sql.NullTime      `json:"updated_at"`
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.queryRow(ctx, q.getUserStmt, GetUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Country,
		&i.City,
		&i.LegalAddress,
		&i.VatNumber,
		&i.Status,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, username, password, email, name, country, city, legal_address, vat_number, status, language, created_at, updated_at
FROM users
WHERE (username = $1 OR email=$1)
AND status = 'active'
`

type GetUserByUsernameOrEmailRow struct {
	ID           int32             `json:"id"`
	Username     string            `json:"username"`
	Password     string            `json:"password"`
	Email        string            `json:"email"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	CreatedAt    sql.NullTime      `json:"created_at"`
	UpdatedAt    sql.NullTime      `json:"updated_at"`
}

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, username string) (GetUserByUsernameOrEmailRow, error) {
	row := q.queryRow(ctx, q.getUserByUsernameOrEmailStmt, GetUserByUsernameOrEmail, username)
	var i GetUserByUsernameOrEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Name,
		&i.Country,
		&i.City,
		&i.LegalAddress,
		&i.VatNumber,
		&i.Status,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUserPassword = `-- name: GetUserPassword :one
SELECT password
FROM users
WHERE id = $1
AND status = 'active'
`

func (q *Queries) GetUserPassword(ctx context.Context, id int32) (string, error) {
	row := q.queryRow(ctx, q.getUserPasswordStmt, GetUserPassword, id)
	var password string
	err := row.Scan(&password)
	return password, err
}

const ListCargoOffers = `-- name: ListCargoOffers :many
SELECT id, created_by, origin_country_id, origin_city_id, destination_country_id, destination_city_id, loading_places, unloading_places, ready_to_load_by, delivery_deadline, load_type, truck_type, weight_t, volume_m3, pallets, palletized, temperature_min_c, temperature_max_c, published_at, expires_at, price, currency, notes, status, created_at, updated_at
FROM cargo_offers
WHERE ($1::int IS NULL OR origin_country_id = $1::int)
  AND ($2::int IS NULL OR origin_city_id = $2::int)
  AND ($3::int IS NULL OR destination_country_id = $3::int)
  AND ($4::int IS NULL OR destination_city_id = $4::int)
  AND ($5::text IS NULL OR load_type = $5::load_type)
  AND ($6::text IS NULL OR truck_type = $6::truck_type)
  AND ($7::text IS NULL OR status = $7::offer_status)
  AND ($8::timestamptz IS NULL OR ready_to_load_by   >= $8::timestamptz)
  AND ($9::timestamptz   IS NULL OR ready_to_load_by   <= $9::timestamptz)
  AND ($10::timestamptz IS NULL OR delivery_deadline >= $10::timestamptz)
  AND ($11::timestamptz   IS NULL OR delivery_deadline <= $11::timestamptz)
ORDER BY created_at DESC
LIMIT $13 OFFSET $12
`

type ListCargoOffersParams struct {
	OriginCountryID      sql.NullInt32  `json:"origin_country_id"`
	OriginCityID         sql.NullInt32  `json:"origin_city_id"`
	DestinationCountryID sql.NullInt32  `json:"destination_country_id"`
	DestinationCityID    sql.NullInt32  `json:"destination_city_id"`
	LoadType             sql.NullString `json:"load_type"`
	TruckType            sql.NullString `json:"truck_type"`
	Status               sql.NullString `json:"status"`
	ReadyFrom            sql.NullTime   `json:"ready_from"`
	ReadyTo              sql.NullTime   `json:"ready_to"`
	DeliveryFrom         sql.NullTime   `json:"delivery_from"`
	DeliveryTo           sql.NullTime   `json:"delivery_to"`
	Offset               int32          `json:"offset"`
	Limit                int32          `json:"limit"`
}

func (q *Queries) ListCargoOffers(ctx context.Context, arg ListCargoOffersParams) ([]CargoOffer, error) {
	rows, err := q.query(ctx, q.listCargoOffersStmt, ListCargoOffers,
		arg.OriginCountryID,
		arg.OriginCityID,
		arg.DestinationCountryID,
		arg.DestinationCityID,
		arg.LoadType,
		arg.TruckType,
		arg.Status,
		arg.ReadyFrom,
		arg.ReadyTo,
		arg.DeliveryFrom,
		arg.DeliveryTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CargoOffer{}
	for rows.Next() {
		var i CargoOffer
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.OriginCountryID,
			&i.OriginCityID,
			&i.DestinationCountryID,
			&i.DestinationCityID,
			&i.LoadingPlaces,
			&i.UnloadingPlaces,
			&i.ReadyToLoadBy,
			&i.DeliveryDeadline,
			&i.LoadType,
			&i.TruckType,
			&i.WeightT,
			&i.VolumeM3,
			&i.Pallets,
			&i.Palletized,
			&i.TemperatureMinC,
			&i.TemperatureMaxC,
			&i.PublishedAt,
			&i.ExpiresAt,
			&i.Price,
			&i.Currency,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListCitiesByCountryID = `-- name: ListCitiesByCountryID :many
SELECT id, name, country_id, latitude, longitude
FROM cities
WHERE country_id=$1
ORDER BY name
`

func (q *Queries) ListCitiesByCountryID(ctx context.Context, countryID int32) ([]City, error) {
	rows, err := q.query(ctx, q.listCitiesByCountryIDStmt, ListCitiesByCountryID, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CountryID,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListCountries = `-- name: ListCountries :many
SELECT id, name, code, alpha3_code, eu_member, continent
FROM countries
ORDER BY id
`

func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.query(ctx, q.listCountriesStmt, ListCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Alpha3Code,
			&i.EuMember,
			&i.Continent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTruckAvailability = `-- name: ListTruckAvailability :many
SELECT id, created_by, start_country_id, start_city_id, end_country_id, end_city_id, available_from, available_to, truck_type, max_weight_t, max_volume_m3, full_load, partial_load, loading_places, unloading_places, published_at, expires_at, poster_name, price_per_km, currency, notes, status, created_at, updated_at
FROM truck_availability
WHERE
  ($1::int IS NULL OR start_country_id = $1::int)
  AND ($2::int IS NULL OR start_city_id = $2::int)
  AND ($3::int IS NULL OR end_country_id = $3::int)
  AND ($4::int IS NULL OR end_city_id = $4::int)

  -- ⬇️ ključna izmena: radimo TEXT poređenje, ne enum kast
  AND ($5::text   IS NULL OR truck_type::text   = $5::text)
  AND ($6::text       IS NULL OR status::text       = $6::text)

  AND ($7::timestamptz IS NULL OR available_from >= $7::timestamptz)
  AND ($8::timestamptz   IS NULL OR available_to   <= $8::timestamptz)
  AND ($9::bool    IS NULL OR full_load    = $9::bool)
  AND ($10::bool IS NULL OR partial_load = $10::bool)
ORDER BY published_at DESC NULLS LAST, id DESC
LIMIT $12 OFFSET $11
`

type ListTruckAvailabilityParams struct {
	StartCountryID sql.NullInt32  `json:"start_country_id"`
	StartCityID    sql.NullInt32  `json:"start_city_id"`
	EndCountryID   sql.NullInt32  `json:"end_country_id"`
	EndCityID      sql.NullInt32  `json:"end_city_id"`
	TruckType      sql.NullString `json:"truck_type"`
	Status         sql.NullString `json:"status"`
	AvailableFrom  sql.NullTime   `json:"available_from"`
	AvailableTo    sql.NullTime   `json:"available_to"`
	FullLoad       sql.NullBool   `json:"full_load"`
	PartialLoad    sql.NullBool   `json:"partial_load"`
	Offset         int32          `json:"offset"`
	Limit          int32          `json:"limit"`
}

func (q *Queries) ListTruckAvailability(ctx context.Context, arg ListTruckAvailabilityParams) ([]TruckAvailability, error) {
	rows, err := q.query(ctx, q.listTruckAvailabilityStmt, ListTruckAvailability,
		arg.StartCountryID,
		arg.StartCityID,
		arg.EndCountryID,
		arg.EndCityID,
		arg.TruckType,
		arg.Status,
		arg.AvailableFrom,
		arg.AvailableTo,
		arg.FullLoad,
		arg.PartialLoad,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TruckAvailability{}
	for rows.Next() {
		var i TruckAvailability
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.StartCountryID,
			&i.StartCityID,
			&i.EndCountryID,
			&i.EndCityID,
			&i.AvailableFrom,
			&i.AvailableTo,
			&i.TruckType,
			&i.MaxWeightT,
			&i.MaxVolumeM3,
			&i.FullLoad,
			&i.PartialLoad,
			&i.LoadingPlaces,
			&i.UnloadingPlaces,
			&i.PublishedAt,
			&i.ExpiresAt,
			&i.PosterName,
			&i.PricePerKm,
			&i.Currency,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUsers = `-- name: ListUsers :many
SELECT id, username, email, name, country, city, legal_address, vat_number, status, language, created_at, updated_at
FROM users
WHERE status = 'active'
ORDER BY id
`

type ListUsersRow struct {
	ID           int32             `json:"id"`
	Username     string            `json:"username"`
	Email        string            `json:"email"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	CreatedAt    sql.NullTime      `json:"created_at"`
	UpdatedAt    sql.NullTime      `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.query(ctx, q.listUsersStmt, ListUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Name,
			&i.Country,
			&i.City,
			&i.LegalAddress,
			&i.VatNumber,
			&i.Status,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateTruckAvailabilityStatus = `-- name: UpdateTruckAvailabilityStatus :one
UPDATE truck_availability
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, created_by, start_country_id, start_city_id, end_country_id, end_city_id, available_from, available_to, truck_type, max_weight_t, max_volume_m3, full_load, partial_load, loading_places, unloading_places, published_at, expires_at, poster_name, price_per_km, currency, notes, status, created_at, updated_at
`

type UpdateTruckAvailabilityStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTruckAvailabilityStatus(ctx context.Context, arg UpdateTruckAvailabilityStatusParams) (TruckAvailability, error) {
	row := q.queryRow(ctx, q.updateTruckAvailabilityStatusStmt, UpdateTruckAvailabilityStatus, arg.ID, arg.Status)
	var i TruckAvailability
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.StartCountryID,
		&i.StartCityID,
		&i.EndCountryID,
		&i.EndCityID,
		&i.AvailableFrom,
		&i.AvailableTo,
		&i.TruckType,
		&i.MaxWeightT,
		&i.MaxVolumeM3,
		&i.FullLoad,
		&i.PartialLoad,
		&i.LoadingPlaces,
		&i.UnloadingPlaces,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.PosterName,
		&i.PricePerKm,
		&i.Currency,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
  username      = COALESCE($1, username),
  email         = COALESCE($2, email),
  name          = COALESCE($3, name),
  country       = COALESCE($4, country),
  city          = COALESCE($5, city),
  legal_address = COALESCE($6, legal_address),
  vat_number    = COALESCE($7, vat_number),
  language      = COALESCE($8, language),
  updated_at       = COALESCE($9, updated_at)
WHERE id = $10
AND status ='active'
RETURNING id, username, email, name, country, city, legal_address, vat_number, status, language, created_at, updated_at
`

type UpdateUserProfileParams struct {
	Username     sql.NullString `json:"username"`
	Email        sql.NullString `json:"email"`
	Name         sql.NullString `json:"name"`
	Country      sql.NullString `json:"country"`
	City         sql.NullString `json:"city"`
	LegalAddress sql.NullString `json:"legal_address"`
	VatNumber    sql.NullString `json:"vat_number"`
	Language     sql.NullString `json:"language"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	ID           int32          `json:"id"`
}

type UpdateUserProfileRow struct {
	ID           int32             `json:"id"`
	Username     string            `json:"username"`
	Email        string            `json:"email"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	CreatedAt    sql.NullTime      `json:"created_at"`
	UpdatedAt    sql.NullTime      `json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.queryRow(ctx, q.updateUserProfileStmt, UpdateUserProfile,
		arg.Username,
		arg.Email,
		arg.Name,
		arg.Country,
		arg.City,
		arg.LegalAddress,
		arg.VatNumber,
		arg.Language,
		arg.UpdatedAt,
		arg.ID,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Country,
		&i.City,
		&i.LegalAddress,
		&i.VatNumber,
		&i.Status,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID     int32             `json:"id"`
	Status models.UserStatus `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.exec(ctx, q.updateUserStatusStmt, UpdateUserStatus, arg.ID, arg.Status)
	return err
}
