// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/aleksjovanovic/cargo-agent/internal/models"
)

const changePassword = `-- name: ChangePassword :exec
UPDATE users
SET password=$2, updated_at=$3
WHERE id = $1
`

type ChangePasswordParams struct {
	ID        int32        `json:"id"`
	Password  string       `json:"password"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) error {
	_, err := q.exec(ctx, q.changePasswordStmt, changePassword, arg.ID, arg.Password, arg.UpdatedAt)
	return err
}

const createCargoOffer = `-- name: CreateCargoOffer :one
INSERT INTO cargo_offers (
    created_by,
    origin_country_id, origin_city_id,
    destination_country_id, destination_city_id,
    loading_places, unloading_places,
    ready_to_load_by, delivery_deadline,
    load_type, truck_type,
    weight_t, volume_m3, pallets, palletized,
    temperature_min_c, temperature_max_c,
    published_at, expires_at,
    price, currency, notes, status
) VALUES (
    $1,
    $2, $3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10, $11,
    $12, $13, $14, $15,
    $16, $17,
    $18, $19,
    $20, $21, $22, $23
)
RETURNING id, created_by, origin_country_id, origin_city_id, destination_country_id, destination_city_id, loading_places, unloading_places, ready_to_load_by, delivery_deadline, load_type, truck_type, weight_t, volume_m3, pallets, palletized, temperature_min_c, temperature_max_c, published_at, expires_at, price, currency, notes, status, created_at, updated_at
`

type CreateCargoOfferParams struct {
	CreatedBy            int32          `json:"created_by"`
	OriginCountryID      int32          `json:"origin_country_id"`
	OriginCityID         int32          `json:"origin_city_id"`
	DestinationCountryID int32          `json:"destination_country_id"`
	DestinationCityID    int32          `json:"destination_city_id"`
	LoadingPlaces        int32          `json:"loading_places"`
	UnloadingPlaces      int32          `json:"unloading_places"`
	ReadyToLoadBy        time.Time      `json:"ready_to_load_by"`
	DeliveryDeadline     time.Time      `json:"delivery_deadline"`
	LoadType             interface{}    `json:"load_type"`
	TruckType            interface{}    `json:"truck_type"`
	WeightT              string         `json:"weight_t"`
	VolumeM3             sql.NullString `json:"volume_m3"`
	Pallets              sql.NullInt32  `json:"pallets"`
	Palletized           sql.NullBool   `json:"palletized"`
	TemperatureMinC      sql.NullString `json:"temperature_min_c"`
	TemperatureMaxC      sql.NullString `json:"temperature_max_c"`
	PublishedAt          sql.NullTime   `json:"published_at"`
	ExpiresAt            sql.NullTime   `json:"expires_at"`
	Price                sql.NullString `json:"price"`
	Currency             sql.NullString `json:"currency"`
	Notes                sql.NullString `json:"notes"`
	Status               interface{}    `json:"status"`
}

func (q *Queries) CreateCargoOffer(ctx context.Context, arg CreateCargoOfferParams) (CargoOffer, error) {
	row := q.queryRow(ctx, q.createCargoOfferStmt, createCargoOffer,
		arg.CreatedBy,
		arg.OriginCountryID,
		arg.OriginCityID,
		arg.DestinationCountryID,
		arg.DestinationCityID,
		arg.LoadingPlaces,
		arg.UnloadingPlaces,
		arg.ReadyToLoadBy,
		arg.DeliveryDeadline,
		arg.LoadType,
		arg.TruckType,
		arg.WeightT,
		arg.VolumeM3,
		arg.Pallets,
		arg.Palletized,
		arg.TemperatureMinC,
		arg.TemperatureMaxC,
		arg.PublishedAt,
		arg.ExpiresAt,
		arg.Price,
		arg.Currency,
		arg.Notes,
		arg.Status,
	)
	var i CargoOffer
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.OriginCountryID,
		&i.OriginCityID,
		&i.DestinationCountryID,
		&i.DestinationCityID,
		&i.LoadingPlaces,
		&i.UnloadingPlaces,
		&i.ReadyToLoadBy,
		&i.DeliveryDeadline,
		&i.LoadType,
		&i.TruckType,
		&i.WeightT,
		&i.VolumeM3,
		&i.Pallets,
		&i.Palletized,
		&i.TemperatureMinC,
		&i.TemperatureMaxC,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.Price,
		&i.Currency,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (user_id, token, valid_until)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, created_at, valid_until
`

type CreateEmailVerificationTokenParams struct {
	UserID     int32     `json:"user_id"`
	Token      string    `json:"token"`
	ValidUntil time.Time `json:"valid_until"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.queryRow(ctx, q.createEmailVerificationTokenStmt, createEmailVerificationToken, arg.UserID, arg.Token, arg.ValidUntil)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ValidUntil,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(username, email, password, name, country, city, legal_address, vat_number, language, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, username, email, name, country, city, legal_address, vat_number, status, language, created_at, updated_at
`

type CreateUserParams struct {
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	Password     string       `json:"password"`
	Name         string       `json:"name"`
	Country      string       `json:"country"`
	City         string       `json:"city"`
	LegalAddress string       `json:"legal_address"`
	VatNumber    string       `json:"vat_number"`
	Language     string       `json:"language"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type CreateUserRow struct {
	ID           int32             `json:"id"`
	Username     string            `json:"username"`
	Email        string            `json:"email"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	CreatedAt    sql.NullTime      `json:"created_at"`
	UpdatedAt    sql.NullTime      `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Name,
		arg.Country,
		arg.City,
		arg.LegalAddress,
		arg.VatNumber,
		arg.Language,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Country,
		&i.City,
		&i.LegalAddress,
		&i.VatNumber,
		&i.Status,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmailVerificationToken = `-- name: DeleteEmailVerificationToken :exec
DELETE FROM email_verification_tokens
WHERE token = $1
`

func (q *Queries) DeleteEmailVerificationToken(ctx context.Context, token string) error {
	_, err := q.exec(ctx, q.deleteEmailVerificationTokenStmt, deleteEmailVerificationToken, token)
	return err
}

const deleteExpiredEmailVerificationTokens = `-- name: DeleteExpiredEmailVerificationTokens :exec
DELETE FROM email_verification_tokens
WHERE valid_until < now()
`

func (q *Queries) DeleteExpiredEmailVerificationTokens(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteExpiredEmailVerificationTokensStmt, deleteExpiredEmailVerificationTokens)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET status = 'deleted',
    deleted_at = $2
WHERE id = $1 AND status <> 'deleted'
`

type DeleteUserParams struct {
	ID        int32        `json:"id"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.exec(ctx, q.deleteUserStmt, deleteUser, arg.ID, arg.DeletedAt)
	return err
}

const getCargoOffer = `-- name: GetCargoOffer :one
SELECT id, created_by, origin_country_id, origin_city_id, destination_country_id, destination_city_id, loading_places, unloading_places, ready_to_load_by, delivery_deadline, load_type, truck_type, weight_t, volume_m3, pallets, palletized, temperature_min_c, temperature_max_c, published_at, expires_at, price, currency, notes, status, created_at, updated_at FROM cargo_offers WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCargoOffer(ctx context.Context, id int32) (CargoOffer, error) {
	row := q.queryRow(ctx, q.getCargoOfferStmt, getCargoOffer, id)
	var i CargoOffer
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.OriginCountryID,
		&i.OriginCityID,
		&i.DestinationCountryID,
		&i.DestinationCityID,
		&i.LoadingPlaces,
		&i.UnloadingPlaces,
		&i.ReadyToLoadBy,
		&i.DeliveryDeadline,
		&i.LoadType,
		&i.TruckType,
		&i.WeightT,
		&i.VolumeM3,
		&i.Pallets,
		&i.Palletized,
		&i.TemperatureMinC,
		&i.TemperatureMaxC,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.Price,
		&i.Currency,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCountryByID = `-- name: GetCountryByID :one
SELECT id, name, code, alpha3_code, eu_member, continent
FROM countries
WHERE id = $1
`

func (q *Queries) GetCountryByID(ctx context.Context, id int32) (Country, error) {
	row := q.queryRow(ctx, q.getCountryByIDStmt, getCountryByID, id)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Alpha3Code,
		&i.EuMember,
		&i.Continent,
	)
	return i, err
}

const getCountryByName = `-- name: GetCountryByName :one
SELECT id, name, code, alpha3_code, eu_member, continent
FROM countries
WHERE Lower(name) = Lower($1)
`

func (q *Queries) GetCountryByName(ctx context.Context, lower string) (Country, error) {
	row := q.queryRow(ctx, q.getCountryByNameStmt, getCountryByName, lower)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Alpha3Code,
		&i.EuMember,
		&i.Continent,
	)
	return i, err
}

const getEmailVerificationToken = `-- name: GetEmailVerificationToken :one
SELECT id, user_id, token, created_at, valid_until
FROM email_verification_tokens
WHERE token = $1
LIMIT 1
`

func (q *Queries) GetEmailVerificationToken(ctx context.Context, token string) (EmailVerificationToken, error) {
	row := q.queryRow(ctx, q.getEmailVerificationTokenStmt, getEmailVerificationToken, token)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ValidUntil,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, name, country, city, legal_address, vat_number, status, language, created_at, updated_at
FROM users
WHERE id = $1
AND status = 'active'
`

type GetUserRow struct {
	ID           int32             `json:"id"`
	Username     string            `json:"username"`
	Email        string            `json:"email"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	CreatedAt    sql.NullTime      `json:"created_at"`
	UpdatedAt    sql.NullTime      `json:"updated_at"`
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Country,
		&i.City,
		&i.LegalAddress,
		&i.VatNumber,
		&i.Status,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, username, password, email, name, country, city, legal_address, vat_number, status, language, created_at, updated_at
FROM users
WHERE (username = $1 OR email=$1)
AND status = 'active'
`

type GetUserByUsernameOrEmailRow struct {
	ID           int32             `json:"id"`
	Username     string            `json:"username"`
	Password     string            `json:"password"`
	Email        string            `json:"email"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	CreatedAt    sql.NullTime      `json:"created_at"`
	UpdatedAt    sql.NullTime      `json:"updated_at"`
}

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, username string) (GetUserByUsernameOrEmailRow, error) {
	row := q.queryRow(ctx, q.getUserByUsernameOrEmailStmt, getUserByUsernameOrEmail, username)
	var i GetUserByUsernameOrEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Name,
		&i.Country,
		&i.City,
		&i.LegalAddress,
		&i.VatNumber,
		&i.Status,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPassword = `-- name: GetUserPassword :one
SELECT password
FROM users
WHERE id = $1
AND status = 'active'
`

func (q *Queries) GetUserPassword(ctx context.Context, id int32) (string, error) {
	row := q.queryRow(ctx, q.getUserPasswordStmt, getUserPassword, id)
	var password string
	err := row.Scan(&password)
	return password, err
}

const listCitiesByCountryID = `-- name: ListCitiesByCountryID :many
SELECT id, name, country_id, latitude, longitude
FROM cities
WHERE country_id=$1
ORDER BY name
`

func (q *Queries) ListCitiesByCountryID(ctx context.Context, countryID int32) ([]City, error) {
	rows, err := q.query(ctx, q.listCitiesByCountryIDStmt, listCitiesByCountryID, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CountryID,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountries = `-- name: ListCountries :many
SELECT id, name, code, alpha3_code, eu_member, continent
FROM countries
ORDER BY id
`

func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.query(ctx, q.listCountriesStmt, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Alpha3Code,
			&i.EuMember,
			&i.Continent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, name, country, city, legal_address, vat_number, status, language, created_at, updated_at
FROM users
WHERE status = 'active'
ORDER BY id
`

type ListUsersRow struct {
	ID           int32             `json:"id"`
	Username     string            `json:"username"`
	Email        string            `json:"email"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	CreatedAt    sql.NullTime      `json:"created_at"`
	UpdatedAt    sql.NullTime      `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Name,
			&i.Country,
			&i.City,
			&i.LegalAddress,
			&i.VatNumber,
			&i.Status,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
  username      = COALESCE($1, username),
  email         = COALESCE($2, email),
  name          = COALESCE($3, name),
  country       = COALESCE($4, country),
  city          = COALESCE($5, city),
  legal_address = COALESCE($6, legal_address),
  vat_number    = COALESCE($7, vat_number),
  language      = COALESCE($8, language),
  updated_at       = COALESCE($9, updated_at)
WHERE id = $10
AND status ='active'
RETURNING id, username, email, name, country, city, legal_address, vat_number, status, language, created_at, updated_at
`

type UpdateUserProfileParams struct {
	Username     sql.NullString `json:"username"`
	Email        sql.NullString `json:"email"`
	Name         sql.NullString `json:"name"`
	Country      sql.NullString `json:"country"`
	City         sql.NullString `json:"city"`
	LegalAddress sql.NullString `json:"legal_address"`
	VatNumber    sql.NullString `json:"vat_number"`
	Language     sql.NullString `json:"language"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	ID           int32          `json:"id"`
}

type UpdateUserProfileRow struct {
	ID           int32             `json:"id"`
	Username     string            `json:"username"`
	Email        string            `json:"email"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	CreatedAt    sql.NullTime      `json:"created_at"`
	UpdatedAt    sql.NullTime      `json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.queryRow(ctx, q.updateUserProfileStmt, updateUserProfile,
		arg.Username,
		arg.Email,
		arg.Name,
		arg.Country,
		arg.City,
		arg.LegalAddress,
		arg.VatNumber,
		arg.Language,
		arg.UpdatedAt,
		arg.ID,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Country,
		&i.City,
		&i.LegalAddress,
		&i.VatNumber,
		&i.Status,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID     int32             `json:"id"`
	Status models.UserStatus `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.exec(ctx, q.updateUserStatusStmt, updateUserStatus, arg.ID, arg.Status)
	return err
}
