// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"

	"github.com/aleksjovanovic/cargo-agent/internal/models"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(username, email, password, name, country, city, legal_address, vat_number, status, language, created, updated)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, username, email, name, country, city, legal_address, vat_number, status, language, created, updated
`

type CreateUserParams struct {
	Username     string            `json:"username"`
	Email        string            `json:"email"`
	Password     string            `json:"password"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	Created      sql.NullTime      `json:"created"`
	Updated      sql.NullTime      `json:"updated"`
}

type CreateUserRow struct {
	ID           int32             `json:"id"`
	Username     string            `json:"username"`
	Email        string            `json:"email"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	Created      sql.NullTime      `json:"created"`
	Updated      sql.NullTime      `json:"updated"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Name,
		arg.Country,
		arg.City,
		arg.LegalAddress,
		arg.VatNumber,
		arg.Status,
		arg.Language,
		arg.Created,
		arg.Updated,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Country,
		&i.City,
		&i.LegalAddress,
		&i.VatNumber,
		&i.Status,
		&i.Language,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, name, country, city, legal_address, vat_number, status, language, created, updated
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID           int32             `json:"id"`
	Username     string            `json:"username"`
	Email        string            `json:"email"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	Created      sql.NullTime      `json:"created"`
	Updated      sql.NullTime      `json:"updated"`
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Country,
		&i.City,
		&i.LegalAddress,
		&i.VatNumber,
		&i.Status,
		&i.Language,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, username, password, email, name, country, city, legal_address, vat_number, status, language, created, updated
FROM users
WHERE username = $1 OR email=$1
`

type GetUserByUsernameOrEmailRow struct {
	ID           int32             `json:"id"`
	Username     string            `json:"username"`
	Password     string            `json:"password"`
	Email        string            `json:"email"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	Created      sql.NullTime      `json:"created"`
	Updated      sql.NullTime      `json:"updated"`
}

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, username string) (GetUserByUsernameOrEmailRow, error) {
	row := q.queryRow(ctx, q.getUserByUsernameOrEmailStmt, getUserByUsernameOrEmail, username)
	var i GetUserByUsernameOrEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Name,
		&i.Country,
		&i.City,
		&i.LegalAddress,
		&i.VatNumber,
		&i.Status,
		&i.Language,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, name, country, city, legal_address, vat_number, status, language, created, updated
FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID           int32             `json:"id"`
	Username     string            `json:"username"`
	Email        string            `json:"email"`
	Name         string            `json:"name"`
	Country      string            `json:"country"`
	City         string            `json:"city"`
	LegalAddress string            `json:"legal_address"`
	VatNumber    string            `json:"vat_number"`
	Status       models.UserStatus `json:"status"`
	Language     string            `json:"language"`
	Created      sql.NullTime      `json:"created"`
	Updated      sql.NullTime      `json:"updated"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Name,
			&i.Country,
			&i.City,
			&i.LegalAddress,
			&i.VatNumber,
			&i.Status,
			&i.Language,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
